# Generated by Django 5.2.5 on 2025-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
