from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("", views.index, name="index"),
    path("admin_dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("user_dashboard/", views.user_dashboard, name="user_dashboard"),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_activity/<int:activity_id>/', views.delete_activity, name='delete_activity'),
    path('delete_travel_tip/<int:tip_id>/', views.delete_travel_tip, name='delete_travel_tip'),
    path('create_user/', views.create_user, name='create_user'),
    path('create_activity/', views.create_activity, name='create_activity'),
    path('create_travel_tip/', views.create_travel_tip, name='create_travel_tip'),   
    path("activities/", views.activity_list, name="activity_list"),
    path("user_list/", views.user_list, name="user_list"),
    path("edit_activity/<int:activity_id>/", views.edit_activity, name="edit_activity"),
    path("edit_user/<int:user_id>/", views.edit_user, name="edit_user"),
    path("edit_profile", views.edit_profile, name="edit_profile"),

    # path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('destination_list/', views.destination_list, name='destination_list'),
    path('create_destination/', views.create_destination, name='create_destination'),
    path('travel_tips/', views.travel_tips_list, name='travel_tips_list'),
    path('discount_list/', views.discount_list, name='discount_list'),
    path('create_discount/', views.create_discount, name='create_discount'),
    path('edit_discount/<int:discount_id>/', views.edit_discount, name='edit_discount'),
    path('delete_discount/<int:discount_id>/', views.delete_discount, name='delete_discount'),
    path('create_interest/', views.create_travel_interest, name='create_travel_interest'),
    path('travel_interest_list/', views.travel_interest_list, name='travel_interest_list'),
    path('create_review/<int:id>/', views.create_review, name='create_review'),
    path('view_reviews/<int:destination_id>/', views.view_reviews, name='view_reviews'),
    path('upload_photos/<int:destination_id>/upload_photos/', views.upload_photos, name='upload_photos'),
    path('view_photos/<int:destination_id>/', views.view_photos, name='view_photos'),
    path('create_service_provider/', views.create_service_provider, name='create_service_provider'),
    path('providers/', views.service_provider_list, name='service_provider_list'),
    path('destination/edit/<int:pk>/', views.edit_destination, name='edit_destination'),
    path('destination/delete/<int:pk>/', views.delete_destination, name='delete_destination'),
    path('provider/edit/<int:pk>/', views.edit_service, name='edit_service'),
    path('provider/delete/<int:pk>/', views.delete_provider, name='delete_provider'),
    path('edit_tip/<int:id>/', views.edit_tip, name='edit_tip'),
    path('delete_tip/<int:id>/', views.delete_tip, name='delete_tip'),
    path('like/<int:photo_id>/', views.like_photo, name='like_photo'),
    path('comment/<int:photo_id>/', views.comment_photo, name='comment_photo'),
]
