# Generated by Django 5.2.5 on 2025-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
