# Generated by Django 5.2.5 on 2025-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0002_assignmentsubmission_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
