# Generated by Django 5.2.5 on 2025-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0003_remove_assignmentsubmission_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='marks',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
