# Generated by Django 5.1.6 on 2025-03-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
