# Generated by Django 5.1.6 on 2025-04-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
    ]
