<?php 
include("header.php");

?>
    <!-- Main Content Section -->
    <main class="mt-4 mb-1">
        <div class="container">
            <!-- Our Story Section -->
            <section id="our-story">
                <h2>Our Story</h2>
                <p>
                    ECO Trade Hub was founded with a vision to revolutionize the automotive industry by promoting the reuse
                    and recycling of used auto parts. Recognizing the vast amount of waste generated by the industry, our
                    founders set out to create a platform where individuals and businesses could easily buy and sell used
                    auto parts. By making it easier to reuse parts, ECO Trade Hub aims to reduce environmental impact and
                    support a more sustainable future.
                </p>
            </section>

            <!-- Mission and Vision Section -->
            <section id="mission-vision">
                <h2>Our Mission & Vision</h2>
                <p>
                    <strong>Mission:</strong> Our mission is to reduce automotive waste and promote environmental
                    sustainability by providing a centralized platform for the exchange of used auto parts. We strive to
                    make the process of buying and selling used parts simple, secure, and accessible for everyone.
                </p>
                <p>
                    <strong>Vision:</strong> We envision a future where the reuse of auto parts is standard practice in the
                    automotive industry, significantly reducing the environmental impact and fostering a culture of
                    sustainability. ECO Trade Hub is committed to leading this change and becoming the go-to platform for
                    all used auto parts transactions.
                </p>
            </section>

            <!-- Our Values Section -->
            <section id="values">
                <h2>Our Core Values</h2>
                <ul>
                    <li><strong>Sustainability:</strong> We are dedicated to reducing waste and promoting the recycling of auto parts.</li>
                    <li><strong>Innovation:</strong> We continuously strive to improve our platform and services to better serve our users.</li>
                    <li><strong>Integrity:</strong> We believe in transparency and honesty in all our transactions and interactions.</li>
                    <li><strong>Community:</strong> We aim to build a strong community of like-minded individuals and businesses who share our commitment to sustainability.</li>
                    <li><strong>Customer Satisfaction:</strong> We are committed to providing excellent service and ensuring the satisfaction of our users.</li>
                </ul>
            </section>

            <!-- Our Team Section -->
            <section id="team">
                <h2>Meet Our Team</h2>
                <p>
                    Our team is made up of passionate individuals who are dedicated to making a positive impact on the
                    environment and the automotive industry. From developers to customer service representatives, every
                    member of the ECO Trade Hub team shares a common goal: to create a platform that not only facilitates
                    transactions but also contributes to a greener future.
                </p>
            </section>

            <!-- Call to Action Section -->
            <section id="cta">
                <h2>Join Us in Making a Difference</h2>
                <p>
                    At ECO Trade Hub, we believe that together we can make a significant impact on the environment and
                    the automotive industry. Join us today and become a part of the movement towards a more sustainable
                    future.
                </p>
                <a href="registration.php" class="btn btn-primary">Join Our Community</a>
            </section>
        </div>
    </main>

</body>
</html>
