# Generated by Django 5.1.5 on 2025-02-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_deleted_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_sender',
        ),
    ]
