# Generated by Django 5.1.5 on 2025-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Cancel', 'Cancel'), ('Rejected', 'Rejected'), ('Exchanged', 'Exchanged')], default='Available', max_length=20),
        ),
    ]
